---
sudo: required
language: python
cache: pip
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker
  - ln -s ansible-role-bitbucket_sources ../bitbucket_sources

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
