---
- name: Converge
  hosts: all
  vars:
    base_dest: /var/scm/bitbucket

    bitbucket_sources_owner: bitbucket-test-user
    bitbucket_sources_group: bitbucket-test-group
    bitbucket_sources_key: examples_bitbucket_ro_access_key
    bitbucket_sources_force: true

  tasks:
    - name: Test bitbucket_sources with git
      include_role:
        name: bitbucket_sources
        allow_duplicates: true
        public: false
      vars:
        bitbucket_sources_repo_account: theatro-noc
        bitbucket_sources_repo_name: example-git
        bitbucket_sources_repo_type: git
        bitbucket_sources_dest: "{{ base_dest }}/theatro-noc/example-git.git"

    - name: Test bitbucket_sources with mercurial
      include_role:
        name: bitbucket_sources
        allow_duplicates: true
        public: false
      vars:
        bitbucket_sources_repo_account: theatro-noc
        kitbucket_sources_repo_name: example-hg
        bitbucket_sources_repo_type: hg
        bitbucket_sources_dest: "{{ base_dest }}/theatro-noc/example-hg.hg"
